### ISSUE TITLE
H2 mode MySQL- ON UPDATE CURRENT_TIMESTAMP not supported

### ISSUE THREAD

**Issue by GoogleCodeExporter** [commandos59/h2database#491]
```
Please send a question to the H2 Google Group or StackOverflow first,
and only then, once you are completely sure it is an issue, submit it here.
The reason is that only very few people actively monitor the issue tracker.

Before submitting a bug, please also check the FAQ:
http://www.h2database.com/html/faq.html

What steps will reproduce the problem?
(simple SQL scripts or simple standalone applications are preferred)
1.Start h2 with MODE=MySQL 
2.CREATE TABLE `test` (
  `id` tinyint(4) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

3.The returned error is : Caused by: org.h2.jdbc.JdbcSQLException: Syntax error 
in SQL statement "CREATE TABLE ""TEST"" ( ""ID"" TINYINT(4) NOT NULL, 
""TIMESTAMP"" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE 
CURRENT_TIMESTAMP, ) ENGINE=INNODB DEFAULT CHARSET=UTF8 "; expected "(, [, ::, 
*, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, NOT, 
NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, 
SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, 
REFERENCES, ,, )"; SQL statement:
CREATE TABLE `test` ( `id` tinyint(4) NOT NULL, `timestamp` timestamp NOT NULL 
DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ) ENGINE=InnoDB DEFAULT 
CHARSET=utf8 [42001-172]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
    at org.h2.message.DbException.get(DbException.java:171)
    at org.h2.message.DbException.getSyntaxError(DbException.java:196)
    at org.h2.command.Parser.getSyntaxError(Parser.java:491)
    at org.h2.command.Parser.read(Parser.java:2853)
    at org.h2.command.Parser.readIfMore(Parser.java:809)
    at org.h2.command.Parser.parseCreateTable(Parser.java:5367)
    at org.h2.command.Parser.parseCreate(Parser.java:3872)
    at org.h2.command.Parser.parsePrepared(Parser.java:324)
    at org.h2.command.Parser.parse(Parser.java:279)
    at org.h2.command.Parser.parse(Parser.java:255)
    at org.h2.command.Parser.prepareCommand(Parser.java:218)
    at org.h2.engine.Session.prepareLocal(Session.java:428)
    at org.h2.engine.Session.prepareCommand(Session.java:377)
    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
    at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.executeSqlScript(ResourceDatabasePopulator.java:186)
    ... 51 more

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system, file
system, and virtual machine?
- H2 v1.3.172 (SVN 4956)
- Windows 7 64bit
- java version "1.7.0_17"
Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)

Do you know a workaround?
No

What is your use case, meaning why do you need this feature?

How important/urgent is the problem for you?

Please provide any additional information below.

```

Original issue reported on code.google.com by `queeq...@gmail.com` on 16 Jul 2013 at 12:46

**Comment by iyurinok** [comment]
```sql

CREATE TABLE IF NOT EXISTS my_table (
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER my_trigger
  BEFORE UPDATE
  ON my_table
  FOR EACH ROW CALL "org.h2.trigger.UpdatedAtTrigger";
```

```java
package org.h2.trigger;

import java.sql.*;
import java.time.Instant;
import org.h2.tools.TriggerAdapter;

public class UpdatedAtTrigger extends TriggerAdapter {

  @Override
  public void fire(Connection conn, ResultSet oldRow, ResultSet newRow) throws SQLException {
    newRow.updateTimestamp("updated_at", Timestamp.from(Instant.now()));
  }
}
```

**Comment by wipu** [comment]
Please, could you simply add support for default values? I don't mind having workarounds, but at the moment H2 doesn't even call my triggers. It instantiates them, and complains if they are not of the correct type and everything. But no call when needed.

EDIT: If I use EACH STATEMENT instead of EACH ROW, I get a call but Connection is the only non-null parameter. No matter if I extend TriggerAdapter or implement Trigger, there is no useful data for the trigger to work.
